### ISSUE TITLE
[Bug] sign up & sign in 안됨

### ISSUE THREAD

**Issue by helkw** [swsnu/swpp2020-team18#20] opened 2020-12-10 10:43 UTC
**Describe the bug**
signup과 signin 버튼이 동작하지 않습니다.

**To Reproduce**
1. signup에서 signup버튼 누르기
2. signin으로 돌아와서 signin 버튼 누르기

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SPICYJO** [comment] 2020-12-15 13:06
Duplicate of issue #21

**Closed by SPICYJO** 2020-12-15 13:06 UTC
Labels: bug
